config/routes.rb
TheNag::Application.routes.draw do

  resources :tasks

  get "dashboard" => "dashboards#dashboard", :as => :dashboard
  put "dashboard/:id/:event_id" => "dashboards#update", :as => :update_group

  root :to => 'pages#home'
  
  resources :groups
  
  
  get "groups/newgrouptask" => "groups#newgrouptask", :as => :new_task
  
  get "groups/new" => "groups#new", :as => :new_group
  
  post "groups/newtask" => "tasks#new_task_for_group", :as => :new_task_for_group
  
  post "groups/destroy" => "groups#destroy", :as => :destroy_task

  resources :users, :except => [:index]
  
  resources :logins, :only => [:new, :create, :destroy]
  
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :user_id, :due
  has_many :groups
  validates :due, date: { after: Proc.new { Time.now }, message: 'must be after today' }, on: :create
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :event_id, :name
  belongs_to :event
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :desc, :done, :group_id
  
  belongs_to :group
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # Assumptions:
  # - "password_digest" is a column
  # - User is asked for a 'password'
  # - Encrypts the password and then stores in the password_digest column
  # - Ensures that 'password_confirmation' field matches 'password'.
  # - 'bcrypt' has been activated in Gemfile
  
  # :password_digest removed from attr_accessible for security
  attr_accessible :fname, :lname, :email, :phone, 
                  :password, :password_confirmation
  
  validates :fname, :presence => true
  validates :lname, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates :phone, :length => {:maximum => 10} 
  # has_secure_password validates that 'password' matches 'password_confirmation'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def authorize
    if current_user.nil?
      redirect_to :new_login
    end
  end
    
  # Return either 'nil' or a User object.
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  
  def logged_in?
      current_user != nil
  end
  
  helper_method :current_user, :logged_in?
  
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

	def dashboard
		if params[:event]
			@selected_event = Event.find(params[:event][:id])
		else
			@selected_event = Event.where("user_id = ?", session[:user_id]).order("due").first
		end

		@event = Event.new

		@groups = Group.order("created_at DESC")

		@task = Task.new
		
	end

	def update
		@group = Group.find(params[:id])
		@group.update_attribute(:event_id, params[:event_id])
    
    @selected_event = Event.find(params[:event_id])
    @event = Event.new
    
    @groups = Group.order("created_at DESC")
    @task = Task.new
    
    render "dashboard"
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
		@event = Event.new
	end

	def show
		@selected_event = Event.find(params[:id])

		render "dashboard"
	end

	def create
		@event = Event.new(params[:event])
		@events = Event.order("due")
		if @event.save
			redirect_to(:dashboard)
		else
			render :template => "dashboards/dashboard"
		end
	end

	def update
		@selected_event = Event.find(params[:id])
		redirect_to(:dashboard)
	end

	def destroy
		Event.find(params[:id]).destroy
		redirect_to(:dashboard)
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  protect_from_forgery
  
  def new
    @group = Group.new
    @task = Task.new
  end
  def create
    @group = Group.new(params[:group])
    @group.save 
    @tasks = Task.where("group_id = #{@group.id}")
    @task = Task.new(:desc => params[:task][:desc], :group_id => @group.id)
    @task.save

    redirect_to(@group) 
 
  end
  def update
    @task = Task.new
    @task_destroy = Task.find(params[:task][:task_id])
    @task_destroy.destroy
    
    @group = Group.find(params[:task][:group_id])
    @tasks = Task.where("group_id = #{@group.id}")
  end
  
  def edit
     @group = Group.find(params[:id])
     @task = Task.new
     @tasks = Task.where("group_id = #{@group.id}")
  
  end
  def destroy
  end
  
  def show

    @group = Group.find(params[:id])
    @tasks = Task.where("group_id = #{@group.id}")
    @task = Task.new

  end
  
  def newgrouptask
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id # <-- a "log in" by authenticating and setting a session variable.
      redirect_to :dashboard
    else
      #raise "Login Failed."
      flash[:notice] = "Login failed, please try again."
      redirect_to :new_login
    end
    #binding.pry
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(:root)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  protect_from_forgery
  
  def home
    # binding.pry
    if session[:user_id]
      # binding.pry
      redirect_to :dashboard
    end
  end
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_filter :authorize, :only => [:new, :edit, :create, :update]
  
  def create
    @tasks = Task.new(params[:task])
    
    if @tasks.save
      redirect_to(:dashboard)
    end
  end
  
  def edit
    @tasks = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.done
      @task.update_attributes({:done => false})
    else
      @task.update_attributes({:done => true})
    end
    redirect_to(:dashboard)
  end
    
  def new
    @tasks = Task.find(params[:id])
    @tasks.update_attributes(params[:task])
    redirect_to(:dashboard)    

    @task = Task.new(params[:task])
    if @task.save 
      redirect_to(:dashboard)
    end
  end
  
  def new_task_for_group
    @task = Task.new(params[:task])
    
    if @task.save
      redirect_to(group_path(@task.group_id))
    end
  end
  
  def show
    
  end
      
  def destroy
    Task.find(params[:id]).destroy
    redirect_to(:dashboard)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    # binding.pry
    @user = User.find(params[:id])
    @user_events = Event.where(:user_id => params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    # binding.pry
    @user = User.new(params[:user])    
    if @user.save
      session[:user_id] = @user.id  # Auto login to session on new user creation
      redirect_to(:dashboard)
    else
      render "new"
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    # binding.pry
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to(:dashboard)
    else
      render "edit"
    end  
  end
  
  def destroy
    @user = User.find(params[:id])
    if session[:user_id] == @user.id
      session[:user_id] = nil
    end
    @user.delete
    redirect_to(:root)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/dashboard.html.erb
<div id="topbannertimes">
  </div>
<h1 class ="animated fadeInDown">Dashboard</h1>


<div class="row">
  <div class="large-6 columns">
    <div class="row">
      <div id="black" class="large-3 columns">...</div>
      <div id="dtitle" class="large-6 columns" style="text-align:center;">MAKE EVENT</div>
      <div id="black" class="large-3 columns">...</div>
    </div>
    
    	<%= form_for @event do |f| %>
    		<% if @event.errors.any? %>
    		  <% @event.errors.full_messages.each do |error_msg| %>
    		    <p><%= error_msg %></p>
    		  <% end %>
    		<% end %>
    		<p>
    			<%= f.text_field :name, :placeholder => "EVENT NAME",:class => "inputtimes5" %>
          
          <div class="row" style="margin-bottom:20px;">
            <div id="black" class="large-3 columns">...</div>
            <div id="dtitle" class="large-6 columns" style="text-align:center;">DUE DATE</div>
            <div id="black" class="large-3 columns">...</div>
          </div>

            <div class="row">
              <div class="small-8 large-8 columns">
                <%= f.text_field :due, :class => "datepicker" %>
                <%= f.hidden_field :user_id, :value => session[:user_id] %>
              </div>
              <div class="small-4 large-4 columns">
                <div style="position:relative; top: 20px;">
                <%= f.submit "Add" %>
                </div>
              </div>
            </div>
            
            
    				
    				<%#= f.date_select :due, start_year: Time.now.year, 
											 use_short_month: true, 
											 order: [:month, :day, :year] %>

    			
    		</p>
    		<p>
    			
    		</p>
    	<% end %>
      
      <div class="row" style="margin-bottom:50px;">
        <div id="black" class="small-3 large-3 columns">...</div>
        <div id="dtitle" class="small-6 large-6 columns" style="text-align:center;">GROUPS</div>
        <div id="black" class="small-3 large-3 columns">...</div>
      </div>
      
      <div class="row" style="width: 200px; display:block; margin: 0 auto;">
        <%= link_to "Create a Group", :new_group, :class => "makegroupbutton" %>
      </div>
    
      <div class="group_list" style="margin-top:60px">
          <% @groups.each do |group| %>
              <div class="row">
                 <div class="small-8 large-8 columns" id ="coolfont" ><%= group.name %></div>
                <div class="small-2 large-2 columns">
                  <% if @selected_event %>
                    <%= link_to "ADD", update_group_path(group.id, @selected_event), :method => :put, :class => "left" %>
                  <% end %>
                </div>
                <div class="small-2 large-2 columns"><%= link_to "Edit", edit_group_path(group.id), :class => "left" %></div>
              </div> 
              <hr>
          <% end %>
          <div id="black" style="margin-bottom: 40px;">
          </div>
      </div>
    
    
  </div>
  <div class="large-6 columns">

    	<%= form_for "sel_event", url: :dashboard, method: :get do |e| %>
    
          
          <div class="row">
            <div class="small-8 large-8 columns">
              <%= collection_select(:event, :id, Event.where("user_id = ?", session[:user_id]), :id, :name, :class => "picker") %>
            </div>
            <div class="small-4 large-4 columns">
              <%= e.submit "PICK"%>
            </div>
          </div>
          
          
    			<%#= e.select "Switch event:", [["Dad", "Fred"], ["Mom", "Wilma"]] %>
    			
    			
    	
    	<% end %>

    	<% if @selected_event %>
    		<%# @events.each do |event| %>
        <div id="eventtitleleft">
    			<h2><%= @selected_event.name %></h2>
    			<p id="coolfont" class="center"><%= @selected_event.due.strftime("%m/%d/%y") %></p>
          
          
    			<p style="text-align:center;"><%= link_to "Delete Event", event_path(@selected_event.id), :method => :delete %></p>
          
        </div>

    			<% @selected_event.groups.each do |group| %>
          
    				<h3 class="group" style="margin-top:20px;"><%= group.name %></h3>
					  <hr>
    					<ul>
    						<% ordered_tasks = group.tasks.order("created_at DESC") %>
    						<% ordered_tasks.each do |task| %>
    							<li class="task">
                      <div class="row">
                        <div class="small-2 large-2 columns">
        									<div class="left checkbox">
        										<%= link_to "Done", task_path(task.id), :method => :put, :class => (task.done ? 'done' : 'not_done') %>
                          </div>
                        </div>
                        <div class="small-6 large-6 columns">
                          <div class="left desc"><%= task.desc %></div>
                        </div>
                        <div class="small-2 large-2 columns">
                          <div class="left"><%= link_to "Delete", task_path(task.id), :method => :delete, :class => "delete" %></div>
                        </div>
                      </div>
    									
    									
    									
    							</li>
    						<% end %> <!-- End of @tasks loop -->
    					</ul>

              <div class="row">
                <%= form_for @task do |t| %>
                <div class="small-8 large-8 columns">
      						<p><%= t.text_field :desc, :value => "Add Task",:class => "inputtimes6"	%></p>
      							 <%= t.hidden_field :done, :value => false %>
      							 <%= t.hidden_field :group_id, :value => group.id %>
                </div>
                <div class="small-4 large-4 columns">
                   <%= t.submit "ADD", :class => 'submit_class_name_here'%>
                </div>
              </div>
    					
    						
    							
    					<% end %>

    			<% end %> <!-- End of @groups loop -->

    	<% else %>

    		<p>No Events!  Nobody is this organized!</p>
    	<% end %>
    
    
    
 

app/views/groups/add.html.erb
<h1>Add</h1>

app/views/groups/edit.html.erb
<div style="margin-top: 100px;">
   <div id="form">
     <img class ="crown" src="/assets/crown.png">
     <h2 class="titlething">Edit Group</h2>
     <div id="insideform">
     <div id="formbackground">
       <p class="showtitle"><%= @group.name %></p>
    
    	   <% @tasks.each do |task|%>
            <%= form_for task, :url => edit_group_path do |f| %>
            <div class="clearfix">
      	   		<p class ="listtext" style="display: inline;text-align:left;"><%= task.desc %></p>
              <p style="float: right;margin-top: -10px;">
                <%= f.hidden_field :task_id, :value => task.id %>
                <%= f.hidden_field :group_id, :value => @group.id %>
                <%= f.submit "X" , :class => "submittimes2"%>
              </p>
            </div>
            <% end %>
    	   <%end%>
         <%= form_for @task, :url => new_task_for_group_path do |f| %>
         <%= f.text_field :desc , :class => "creategrouptasks",:placeholder => "ADD TASK"%>
         <%= f.hidden_field :group_id, :value => @group.id %>
         <%= f.hidden_field :id, :value => @group.id %>
         <%= f.hidden_field :done, :value => false %>
         <%= f.submit "Add", :class => "submittimes"%>
         <% end %>
         
         <a href="/dashboard">
         <button class="buttontimes" type="button">FINISH</button>
         </a>
       
    
     </div>
     </div>
   </div>
</div>

app/views/groups/new.html.erb
<div  style="margin-top: 100px;">
   <div id="form">
     <img class ="crown" src="/assets/crown.png">
     <h2 class="titlething">Create Group</h2>
     <div id="formbackground6" style = "max-width:360px !important;">
       
       <%= form_for @group do |f| %>
         <p style="margin-top: 20px;">
           <%= f.text_field :name, :class => "inputtimes1",:placeholder => "Name" %>
         </p>
         <%= fields_for @task do |t|%>
           <%= t.text_field :desc , :class => "creategrouptasks", :placeholder => "Task 1"%>

         <% end %>


         <%= f.submit "Add", :class => "submittimes6"%>
       <% end %>
    
     </div>
   </div>
</div>

app/views/groups/show.html.erb
<div style="margin-top: 100px;">
   <div id="form">
     <img class ="crown" src="/assets/crown.png">
     <h2 class="titlething">New Group</h2>
     <div id="insideform">
     <div id="formbackground">
       <p class="showtitle"><%= @group.name %></p>
       
    	   <% @tasks.each do |task|%>
            <%= form_for task, :url => edit_group_path do |f| %>
            <div class="clearfix">
      	   		<p class ="listtext" style="display: inline;text-align:left;"><%= task.desc %></p>
              <p style="float: right;margin-top: -10px;">
                <%= f.hidden_field :task_id, :value => task.id %>
                <%= f.hidden_field :group_id, :value => @group.id %>
                <%= f.submit "X" , :class => "submittimes2"%>
              </p>
            </div>
            <% end %>
    	   <%end%>
         
         <%= form_for @task, :url => new_task_for_group_path do |f| %>
         <div class="row">
           <div class="small-8 large-8 columns">
             <%= f.text_field :desc , :class => "creategrouptasks2",:placeholder => "ADD TASK"%>
             <%= f.hidden_field :group_id, :value => @group.id %>
             <%= f.hidden_field :id, :value => @group.id %>
             <%= f.hidden_field :done, :value => false %>
           </div>
           <div class="small-4 large-4 columns">
               <%= f.submit "Add", :class => "submittimes"%>
           </div>
         </div>
         
         
        
       
         <% end %>
         <a href="/dashboard">
         <button class="buttontimes" type="button">FINISH</button>
         </a>
       
    
     </div>
     </div>
   </div>
</div>

app/views/groups/update.html.erb
<div style="margin-top: 100px;">
   <div id="form">
     <img class ="crown" src="/assets/crown.png">
     <h2 class="titlething">Update Group</h2>
     <div id="insideform">
     <div id="formbackground">
   
         <p class="showtitle"><%= @group.name %></p>
       
     	   <% @tasks.each do |task|%>
             <%= form_for task, :url => edit_group_path do |f| %>
             <div class="clearfix">
       	   		<p class ="listtext" style="display: inline;text-align:left;"><%= task.desc %></p>
               <p style="float: right;margin-top: -10px;">
                 <%= f.hidden_field :group_id, :value => @group.id %>
                 <%= f.submit "X" , :class => "submittimes2"%>
               </p>
             </div>
             <% end %>
     	   <%end%>
         <%= form_for @task, :url => new_task_for_group_path do |f| %>
         <%= f.text_field :desc , :class => "creategrouptasks",:placeholder => "ADD TASK"%>
         <%= f.hidden_field :group_id, :value => @group.id %>
         <%= f.hidden_field :id, :value => @group.id %>
         <%= f.hidden_field :done, :value => false %>
         <%= f.submit "Add", :class => "submittimes"%>
         <% end %>
       <a href="/dashboard">
       <button class="buttontimes" type="button">FINISH</button>
       </a>
    
     </div>
     </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheNag</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body id=“<%= params[:controller] %>”>
  
  <div class="row">
    <% if current_user %>
    <div class="large-6 columns">
        <h4 style="text-align:center;" class="show-for-small-only">The Nag</h4>
      <h4 style="position:relative; bottom: -7px;" class="hide-for-small-only"> <%= "#{current_user.fname}" %>'s Nag</h4>
    </div>
    <div class="large-6 columns">
      <div class="hide-for-small-only" id='loggednav'>
        <%= link_to(" Log Out ", login_path(current_user.id), :method => :delete) %>
        
        <%= link_to(" Account ", user_path(current_user.id)) %>
        
        <%= link_to(" Dashboard ", :dashboard) %>
    
     
    
      </div>
      <div class="show-for-small-only" id='loggednav2'>
        <%= link_to(" Log Out ", login_path(current_user.id), :method => :delete) %>
        -
        
        <%= link_to(" Account ", user_path(current_user.id)) %>
        -
        <%= link_to(" Dashboard ", :dashboard) %>
    
     
    
      </div>
       <% end %>
      
    </div>
  </div>
  
        
    
<%= yield %>

</body>
</html>

app/views/logins/new.html.erb
<div id="paddingtimes">
  <img class ="crown3 animated bounce" src="/assets/crown.png">
  <h1 class="animated fadeInDown">Log In</h1>

  <%# This is just a plan-ol' HTML form maker: %>

  <div class="animated fadeInDown" id="loginform">
    <%= form_tag logins_path do %>
  
      <p style="margin-top:15px;">
      
        <%= text_field_tag :email, nil, :placeholder => 'EMAIL',:class => "newuserinput" %>
      </p>
      
  
      <p>
        <%= password_field_tag :password, nil, :placeholder => 'PASSWORD',:class => "newuserinput"%>
        
        
      </p>
  
      <%= submit_tag "Log In" %>
    <% end %>
    
    <% if flash[:notice] %>
      <div style="color:white;">
        <p class="center notice"><%= flash[:notice] %></p>
        <p class="center notice">- OR -</p>
        <div class="buttonadd">
          <%= link_to "SIGN UP", :new_user %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/home.html merge copy.erb
<<<<<<< HEAD
<html>
  <head>
    
    <%= stylesheet_link_tag "home.css" %>

 <!-- Removed the <p> tag surrounding the title string. 
   It's not needed and looks awkward in the window title. -->   
    <title>
      The Nag
    </title>
  </head>
  <body>
    
    <div>
    <img class ="logo" src="/assets/largelogo.png" style=" max-width: 350px; display:block; margin: 0 auto;margin-top: 100px;">
    </div>
    
    <div>
      <p class = "center" > 
=======
    <div id="topbannertimes">
      <div id="innerbanner">
>>>>>>> master
        <%= link_to "SIGN UP", :new_user %> | 
        <% if session[:user_id] %>
          <%= link_to "Dashboard", :dashboard %>
        <% else %>
          <%= link_to "LOG IN", :new_login %>
        <% end %>
<<<<<<< HEAD
      </p>
      <% if flash[:notice] %>
        <p class="center notice"><%= flash[:notice] %></p>
      <% end %>
    </div>
    
<!--
     <p><em>For testing, the <strong>session[:user_id] == 
        <%= session[:user_id] || "NONE" %> </strong></em></p> 
-->
      
  </body>
</html>
=======
        </div>
    </div>



    <div>
      <img class ="logo" src="/assets/largelogo.png" style=" max-width: 350px; display:block; margin: 0 auto;margin-top: 150px;">
    
>>>>>>> master

app/views/pages/home.html.erb
    <div id="topbannertimes">
      <div id="innerbanner">

      <% if !current_user %>
        <%= link_to "SIGN UP", :new_user %> | 
        <% link_text = session[:try_again] ? "SIGN IN (try again)" : "SIGN IN" %>
        <% if session[:user_id] %>
          <%= link_to "Dashboard", :dashboard %>
        <% else %>
          <%= link_to link_text, :new_login %>
        <% end %>
      <% end %>
        </div>
    </div>



    <div>
      <img class ="logo animated fadeInDown" src="/assets/largelogo.png" style=" max-width: 350px; display:block; margin: 0 auto;margin-top: 150px;">
      
      <% if flash[:notice] %>
        <p class="center notice"><%= flash[:notice] %></p>
      <% end %>
    

    </div>

app/views/tasks/edit.html.erb
<%= form_for @tasks do |f| %>
  <p>  
    <%= f.text_field :description %>
  </p>
  
  <%= f.submit %>
<% end %>

app/views/tasks/new.html.erb
<%= form_for @tasks do |f| %>
  <!-- fields in  task table description:string, done:boolean, category_id:integer -->
  <p>
    <%= f.check_box :done %>
  
    <%= f.text_field :description %>
  </p>
  
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1>working</h1>

app/views/users/_form.html.erb
  
  <% if @user.errors.any? %>
    <div id="account_error">
      <% @user.errors.full_messages.each do |err| %>
        <p><%= err %></p>
      <% end %>    
    </div>  
  <% end %>

  <!-- :fname, :lname, :email, :phone, :password, :password_confirmation -->

  <div id="newform">
    <%= form_for @user do |f| %>
      <p>
        <%= f.text_field :fname, :placeholder => "FIRST NAME",:class => "newuserinput",:class => "placeholder"%>
      </p>
  
      <p>

        <%= f.text_field :lname, :placeholder => "LAST NAME",:class => "newuserinput",:class => "placeholder"  %>
      </p>
  
      <p>

        <%= f.text_field :email, :placeholder => "EMAIL",:class => "newuserinput",:class => "placeholder" %>
      </p>
  
      <p>
        <%= f.text_field :phone, :placeholder => "PHONE NUMBER",:class => "newuserinput",:class => "placeholder" %>
      </p>
  
      <p>
        <%= f.password_field :password, :placeholder => "PASSWORD",:class => "newuserinput",:class => "placeholder" %>
      </p>
  
      <p>
        <%= f.password_field :password_confirmation, :placeholder => "CONFIRM PASSWORD",:class => "newuserinput",:class => "placeholder" %>
      </p>

  
      <%= f.submit "SAVE",:class => "newuserinput"%>

<% end %>


 </div>

app/views/users/edit.html.erb
<img class ="crown2 animated bounce" src="/assets/crown.png" style="position:relative;top: 50px; left: -58px;">
<h1 class ="animated fadeInDown">Edit</h1>



<div id="center" class ="animated fadeInUp">
    <%= render :partial => "form" %>
</div>

app/views/users/new.html.erb
<img class ="crown2 animated bounce" src="/assets/crown.png">
<h1 class ="animated fadeInDown">Sign Up</h1>



<div id="center" class ="animated fadeInUp">
    <%= render :partial => "form" %>
</div>

app/views/users/show.html.erb
<div id="topbannertimes">
</div>
<img class ="crown2 animated bounce" src="/assets/crown.png">
<h3>Account Info</h3>
<div class ="animated fadeInDown" id="formbackground2">
  <p id ="titlestuffs" >User Name </p><p id="centertext"><%= @user.fname %> <%= @user.lname %></p>
  <p id ="titlestuffs" >Email</p> <p id="centertext"><%= @user.email %></p>
  <p id ="titlestuffs" >Phone </p> <p id="centertext"><%= number_to_phone(@user.phone, area_code: true) %></p>
  <hr>
  <button><%= link_to("EDIT", edit_user_path(@user.id)) %></button>
  <button><%= link_to("DELETE ACCOUNT", user_path(@user.id), :method => "delete") %></button>
</div>